spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "698549024586-130r7v6dnmdkm23rthbf1ns81qjqrk0p.apps.googleusercontent.com"
            client-secret: "a6F1IGaNsTRHyCu-YiWTzCo1"
            scope: "profile,email"

          naver:
            client-id: "2HSIpJO2aV30ZwUK1NO9"
            client-secret: "znq3eZFqXW"
            redirect_uri_template: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization_grant_type: "authorization_code"
            scope: "name,email,profile_image"
            client-name: "Naver"

        provider:
          naver:
            authorization_uri: "https://nid.naver.com/oauth2.0/authorize"
            token_uri: "https://nid.naver.com/oauth2.0/token"
            user-info-uri: "https://openapi.naver.com/v1/nid/me"
            user_name_attribute: "response"
